services:
  mysql:
    image: 'mysql:9.2'
    restart: always
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE_NAME}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:3306'
    networks:
      - backend

  redis:
    image: 'redis:7.2'
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - backend

networks:
  backend:
    driver: bridge
