server:
  port: ${PORT}
  servlet:
    context-path: /potteryshop

spring:
  application:
    name: PotteryShop
  
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESSKEY}
  secretKey: ${MINIO_SECRETKEY}
  bucketName: ${MINIO_BUCKETNAME}

jwt:
  signerKey: ${SIGNERKEY}
  valid-duration: 3600
  refreshable-duration: 7200
  reset-duration: 3600

